server:
  port: '8080'

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
   name: Api gateway Service
   description: Hi Tech bank API
   version: 1.0.0         

spring:
  cloud:
    gateway:
      routes[0]:
        id: discovery-service
        predicates[0]: Path=/eureka/web
        filters[0]: SetPath=/
        uri: http://localhost:8081
      routes[1]:
        id: discovery-service-static
        uri: http://localhost:8081
        predicates[0]: Path=/eureka/**         
      routes[2]:
        uri: lb://onboard-user-service
        id: onboard-user-service
        predicates[0]: Path=/onBoardingService/**
      routes[3]:
        predicates[0]: Path=/authentication/**
        id: authentication-jwt-service
        uri: lb://authentication-jwt-service
      routes[4]:
        uri: lb://redis-cache-service
        id: redis-cache-service
        predicates[0]: Path=/redisCache/**
      routes[5]:
        uri: lb://config-service
        id: config-service
        predicates[0]: Path=/configService/**
      routes[6]:
        uri: lb://aws-service
        id: aws-service
        predicates[0]: Path=/awsService/**
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9411/


logging:
  level:
    org:
      spring:
        security: TRACE
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionRouteLocator: INFO
            nodeValue: TRACE
    root: INFO
allowedUrls:
  http://localhost:4200,http://localhost:80,http://localhost
jwtKey: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4 



