server:
  port: 0
  servlet:
    context-path: /authentication

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
   name: Authentication Service
   description: Hi Tech bank API
   version: 1.0.0

spring:
  datasource:
    username: username
    url: jdbc:mysql://192.168.23.1:3306/eazybank
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'