server:
  port: 0
  servlet:
    context-path: /onBoardingService

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

info:
  app:
   name: On boarding user Service
   description: Hi Tech bank API
   version: 1.0.0        

spring:
  datasource:
    url: jdbc:mysql://192.168.0.105:3306/high_tech_bank_onboard
    username: sammy
    password: Ch@ddu001
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9411/          

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
           sql: trace

redis-app:
 saveApplication: http://redis-cache-service/redisCache/public/saveApplication
 getApplication: http://redis-cache-service/redisCache/public/findApplicationById
aws:
 fileUpload: http://aws-service/awsService/public/uploadToS3
 postSNS: http://aws-service/awsService/public/publishToSNS

demo:
  property: Shamit-amit-Ne