demo:
  property: Shamit-amit-Ne

server:
  port: 0
  servlet:
    context-path: /onBoardingService

management:
  endpoints:
    web:
      exposure:
        include: refresh    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

spring:
  datasource:
    url: jdbc:mysql://192.168.23.1:3306/high_tech_bank_onboard
    username: username
    password: password
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
           sql: trace